(function(d){function l(){window.location.hash==c.permalink_hash_lat&&f.C2L.call(this);window.location.hash==c.permalink_hash_cyr&&f.L2C.call(this)}function u(){if("onhashchange"in window)window.addEventListener?window.addEventListener("hashchange",l,!1):window.attachEvent&&window.attachEvent("onhashchange",l);else{var b=location.href;setInterval(function(){var a=location.href;b!==a&&(b=a,l())},100)}l();return window.location.hash==c.permalink_hash_lat||window.location.hash==c.permalink_hash_cyr?
!0:!1}function m(b){var a="; ";c.cookie_duration&&(a=new Date,a.setDate(a.getDate()+c.cookie_duration),a="; expires="+a.toGMTString()+"; ");document.cookie="CyrLatConverterSelected="+b+a+"path=/"}function v(){for(var b=document.cookie.split(";"),a=0;a<b.length;a++){for(var c=b[a];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf("CyrLatConverterSelected="))return c.substring(24,c.length)}return null}function t(b){var a="on"==c.ignore_list_include_unicode?"[^0-9a-zA-Z\u0400-\u04ff_\u010d\u010c\u0107\u0106\u017e\u017d\u0161\u0160\u0111\u0110]+":
"[^0-9a-zA-Z_\u010d\u010c\u0107\u0106\u017e\u017d\u0161\u0160\u0111\u0110]+";if(3=="test string".split(/([^a-z])/).length)return b.split(RegExp("("+a+")","i"));regex=RegExp(a,"gi");var a=0,e=b.split(regex);b=b.match(regex);var d=[];if(0==e.length)return b;if(null==b)return e;if(b.length==e.length+1){for(a=0;a<e.length;a++)d.push(b[a]),d.push(e[a]);d.push(b[a])}else if(b.length==e.length)if(-1<e[0].indexOf(b[0]))for(a=0;a<b.length;a++)d.push(b[a]),d.push(e[a]);else for(a=0;a<b.length;a++)d.push(e[a]),
d.push(b[a]);else{d.push(e[0]);for(a=0;a<b.length;a++)d.push(b[a]),d.push(e[a+1])}return d}function p(b){var a,c,n,g,f=t(b);d.each(f,function(b,h){"undefined"!=typeof CyrLatIgnoreList&&h.toString().toLowerCase()in CyrLatIgnoreList?f[b]=""==CyrLatIgnoreList[h.toString().toLowerCase()]?h:CyrLatIgnoreList[h.toString().toLowerCase()]:(g=!0,"undefined"!=typeof CyrLatIgnore_doubleletters&&h.toString().toLowerCase()in CyrLatIgnore_doubleletters&&(g=!1),"undefined"!=typeof CyrLatIgnore_doubleletters_base&&
d.each(CyrLatIgnore_doubleletters_base,function(a){if(-1<h.toString().toLowerCase().indexOf(a))return g=!1}),a=h.split(""),d.each(a,function(b,d){c=!1;if(q[d]&&g&&(n=a[b+1])&&q[d][n])a[b]=q[d][n],a[b+1]="",c=!0;c||(a[b]=r[d]&&""!=r[d]?r[d]:d)}),f[b]=a.join(""))});return f.join("")}function s(b){var a;if("undefined"!=typeof CyrLatIgnore){var c=t(b);d.each(c,function(b,g){g.toString().toLowerCase()in CyrLatIgnore?c[b]=""==CyrLatIgnore[g.toString().toLowerCase()]?g:CyrLatIgnore[g.toString().toLowerCase()]:
(a=g.split(""),d.each(a,function(b,c){a[b]=j[c]&&""!=j[c]?j[c]:c}),c[b]=a.join(""))});return c.join("")}a=b.split("");d.each(a,function(b,c){a[b]=j[c]&&""!=j[c]?j[c]:c});return a.join("")}var c={cookie_duration:7,parent_class_ignore:"",permalink_hash_lat:"#lat",permalink_hash_cyr:"#cyr",permalink_hash:"off",ignore_list_include_unicode:"on",benchmark:"off",benchmark_eval:"console.log('Execution time: %s%')",button_cyr:"",button_lat:"",button_default:""},r={a:"\u0430",b:"\u0431",c:"\u0446",d:"\u0434",
e:"\u0435",f:"\u0444",g:"\u0433",h:"\u0445",i:"\u0438",j:"\u0458",k:"\u043a",l:"\u043b",m:"\u043c",n:"\u043d",o:"\u043e",p:"\u043f",q:"",r:"\u0440",s:"\u0441",t:"\u0442",u:"\u0443",v:"\u0432",w:"",x:"",y:"",z:"\u0437",A:"\u0410",B:"\u0411",C:"\u0426",D:"\u0414",E:"\u0415",F:"\u0424",G:"\u0413",H:"\u0425",I:"\u0418",J:"\u0408",K:"\u041a",L:"\u041b",M:"\u041c",N:"\u041d",O:"\u041e",P:"\u041f",Q:"",R:"\u0420",S:"\u0421",T:"\u0422",U:"\u0423",V:"\u0412",W:"",X:"",Y:"",Z:"\u0417","\u010d":"\u0447","\u0107":"\u045b",
"\u0111":"\u0452","\u017e":"\u0436","\u0161":"\u0448","\u010c":"\u0427","\u0106":"\u040b","\u0110":"\u0402","\u017d":"\u0416","\u0160":"\u0428"},j={"\u0430":"a","\u0431":"b","\u0446":"c","\u0434":"d","\u0435":"e","\u0444":"f","\u0433":"g","\u0445":"h","\u0438":"i","\u0458":"j","\u043a":"k","\u043b":"l","\u043c":"m","\u043d":"n","\u043e":"o","\u043f":"p","\u0440":"r","\u0441":"s","\u0442":"t","\u0443":"u","\u0432":"v","\u0437":"z","\u0410":"A","\u0411":"B","\u0426":"C","\u0414":"D","\u0415":"E","\u0424":"F",
"\u0413":"G","\u0425":"H","\u0418":"I","\u0408":"J","\u041a":"K","\u041b":"L","\u041c":"M","\u041d":"N","\u041e":"O","\u041f":"P","\u0420":"R","\u0421":"S","\u0422":"T","\u0423":"U","\u0412":"V","\u0417":"Z","\u0447":"\u010d","\u045b":"\u0107","\u0452":"\u0111","\u0436":"\u017e","\u0448":"\u0161","\u0459":"lj","\u045a":"nj","\u0452":"\u0111","\u045f":"dz","\u0427":"\u010c","\u040b":"\u0106","\u0402":"\u0110","\u0416":"\u017d","\u0428":"\u0160","\u0409":"Lj","\u040a":"Nj","\u0402":"\u0110","\u040f":"D\u017e"},
q={l:{j:"\u0459"},n:{j:"\u045a"},d:{j:"\u0452",z:"\u045f","\u017e":"\u045f"},L:{j:"\u0409",J:"\u0409"},N:{j:"\u040a",J:"\u040a"},D:{j:"\u0402",J:"\u0402",z:"\u040f",Z:"\u040f","\u017e":"\u040f","\u017d":"\u040f"}},k=!1,f={init:function(b){b&&d.extend(c,b);""!=c.button_cyr&&("#"!=c.button_cyr.charAt(0)&&(c.button_cyr="#"+c.button_cyr),d(c.button_cyr).click(function(){d.CyrLatConverter("L2C")}));""!=c.button_lat&&("#"!=c.button_lat.charAt(0)&&(c.button_lat="#"+c.button_lat),d(c.button_lat).click(function(){d.CyrLatConverter("C2L")}));
""!=c.button_default&&("#"!=c.button_default.charAt(0)&&(c.button_default="#"+c.button_default),d(c.button_default).click(function(){d.CyrLatConverter("default")}));if("on"==c.benchmark.toString().toLowerCase()){var a=(new Date).getTime();k=!0}b=!1;"on"==c.permalink_hash.toLowerCase()&&(b=u());var e="";0<c.cookie_duration&&(e=v());!1==b&&("L2C"==e||"C2L"==e)&&f[e].call(this);"on"==c.benchmark.toString().toLowerCase()&&(eval(c.benchmark_eval.replace("%s%",(new Date).getTime()-a+"ms")),k=!1);return!0},
L2C:function(){if("on"==c.benchmark.toString().toLowerCase()&&!k)var b=(new Date).getTime();d(".CyrLatConvert").each(function(){d(this).wrapInner('<span id="CyrLatWrap" />');d(this).find(":not(iframe,script,style,pre,code,.CyrLatIgnore)").contents().filter(function(){var a;if(a=3==this.nodeType){var b=c.parent_class_ignore.split(",");d.each(b,function(a,c){b[a]=d.trim(c)});a:{for(a=this;a.parentNode;){if(a.className&&0<=jQuery.inArray(a.className,b)){a=!0;break a}a=a.parentNode}a=!1}a=!a}return a?
("undefined"!=typeof this.textContent?this.textContent=p(this.textContent):"undefined"!=typeof this.innerText?this.innerText=p(this.innerText):"undefined"!=typeof this.nodeValue&&(this.nodeValue=p(this.nodeValue)),!0):!1})});m("L2C");"on"==c.benchmark.toString().toLowerCase()&&!k&&eval(c.benchmark_eval.replace("%s%",(new Date).getTime()-b+"ms"));return!0},C2L:function(){if("on"==c.benchmark.toString().toLowerCase()&&!k)var b=(new Date).getTime();d(".CyrLatConvert").each(function(){d(this).wrapInner('<span id="CyrLatWrap" />');
d(this).find(":not(iframe,script,style,pre,code,.CyrLatIgnore)").contents().filter(function(){return 3==this.nodeType?("undefined"!=typeof this.textContent?this.textContent=s(this.textContent):"undefined"!=typeof this.innerText?this.innerText=s(this.innerText):"undefined"!=typeof this.nodeValue&&(this.nodeValue=s(this.nodeValue)),!0):!1})});m("C2L");"on"==c.benchmark.toString().toLowerCase()&&!k&&eval(c.benchmark_eval.replace("%s%",(new Date).getTime()-b+"ms"));return!0}};d.CyrLatConverter=function(b){"undefined"===
typeof b||"object"===typeof b||!b?f.init.apply(this,arguments):"default"==b.toString().toLowerCase()?(m("default"),c.permalink_hash="on",window.location.hash="",location.reload(!0)):f[b]?"on"==c.permalink_hash.toLowerCase()?"L2C"==b.toString().toUpperCase()?window.location.hash=c.permalink_hash_cyr:"C2L"==b.toString().toUpperCase()&&(window.location.hash=c.permalink_hash_lat):f[b].call(this):d.error("Unknown call to "+b);return!1}})(jQuery);
